/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airlink-unit.glb -o scratch-model.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Cylinder-Mesh']: THREE.Mesh
    ['Cylinder-Mesh_1']: THREE.Mesh
    ['Cylinder-Mesh_2']: THREE.Mesh
    ['Cylinder-Mesh_3']: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Blade: THREE.MeshStandardMaterial
    Cage: THREE.MeshStandardMaterial
    Inside: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/airlink-unit.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cylinder-Mesh'].geometry} material={materials.Body} />
      <mesh geometry={nodes['Cylinder-Mesh_1'].geometry} material={materials.Blade} />
      <mesh geometry={nodes['Cylinder-Mesh_2'].geometry} material={materials.Cage} />
      <mesh geometry={nodes['Cylinder-Mesh_3'].geometry} material={materials.Inside} />
    </group>
  )
}

useGLTF.preload('/airlink-unit.glb')
